### ISSUE TITLE
B27

### ISSUE THREAD

**Issue by lucasecortes** [lucasecortes/mytinerary-back#40]
Modificar el modelo User con los siguientes campos como requeridos:

- From: alojará todos los tipos de registro de un usuario (formulario,facebook,google,etc).
- Code: de tipo string, se utilizará como código de verificación.
- Verified: por default en false y cuando el usuario se verifique cambia a true.
- loggedIn: por default en false y cuando el usuario esté logueado cambiará a true.

Editar los usuarios ya creados con esta nueva propiedad

**Comment by ReyesRRV** [comment]
Izii pizzi ^^
